In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import norm
from scipy import optimize
from calendar import *
from datetime import *

df = pd.read_excel("Exam Data.xlsx", index_col = 0, sheet_name = "Histo underlying")
STOXX_DEC = df.iloc[1:,0]
STOXX_DEC.index.name = "Date"

STOXX = df.iloc[1:,3].dropna()
STOXX.index.name = "Date"

In [2]:
df_call_put = pd.read_excel("Exam Data.xlsx", index_col = 1, sheet_name = "Call-Put Price").drop("CALL", axis = 1).dropna()
df_call = df_call_put.iloc[:9]
df_put = df_call_put.iloc[10:]

In [112]:
np.sqrt(252) * STOXX.pct_change(1).std()

0.23086809544365078

In [7]:
def BSClosedForm(S_0, K, r, sigma, T, isCall):
        d1 = (np.log(S_0/K) + (r + 0.5 * sigma**2)*T)/(sigma * np.sqrt(T))
        d2 = d1 - sigma * np.sqrt(T)
        if isCall:
            return S_0 * norm.cdf(d1) - np.exp(-r * T) * K * norm.cdf(d2)
        else:
            return -S_0 * norm.cdf(-d1) + np.exp(-r * T) * K * norm.cdf(-d2)

In [26]:
K, end_date = 3400, pd.datetime(2021, 6, 18)
S_0 = 3956.77
curr_date = pd.datetime(2021, 4, 7)
r = 0.01
isCall = True
T = (end_date - curr_date).days/252

def IV(S_0, curr_date, r, K, end_date, isCall):
    T = (end_date - curr_date).days/252
    if isCall:
        p = df_call.loc[K,end_date] * S_0
    else:
        p = df_put.loc[K,end_date] * S_0
    a, b = 0.00000000001, 1
    f = lambda x: BSClosedForm(S_0, K, r, x, T, isCall) - p
    sol = optimize.brentq(f, a, b)
    return sol

In [31]:
print(df_call.loc[K,end_date] * S_0)
BSClosedForm(S_0, K, r, 0.1, T, isCall)

531.0664785353534


566.5799143202771

In [32]:
df_call

2021-06-18 00:00:00 2021-12-17 00:00:00 2022-06-17 00:00:00  \
K/T                                                                
4200          0.00217172           0.0171591           0.0273359   
4000           0.0132702           0.0370328           0.0463384   
3800           0.0442045           0.0660985           0.0725758   
3600           0.0869444            0.102374            0.104747   
3400            0.134217            0.143434            0.141705   
3200            0.183283            0.187715            0.182462   
3000             0.23303            0.233889            0.225316   
2800            0.283068            0.281414            0.270404   
2600               0.325            0.329874               0.315   

     2022-12-16 00:00:00 2023-12-15 00:00:00 2024-12-20 00:00:00  \
K/T                                                                
4200           0.0385354           0.0509722             0.06125   
4000           0.0580429           0.0691919           0.0784217   
3800           0.0834091           0.0917551           0.0992298   
3600            0.113737            0.118712            0.124533   
3400            0.148308            0.150492            0.152891   
3200            0.187134            0.185139            0.184583   
3000            0.228384            0.221995            0.219432   
2800            0.271919                0.27            0.255795   
2600            0.317058               0.315               0.305   

     2025-12-19 00:00:00 2026-12-18 00:00:00  
K/T                                           
4200               0.071              0.0815  
4000               0.088               0.094  
3800               0.102               0.105  
3600               0.129               0.131  
3400               0.155               0.157  
3200              0.1836              0.1826  
3000               0.218               0.025  
2800               0.253               0.251  
2600               0.302                 0.3

In [33]:
from scipy import interpolate
x = np.arange(-5.01, 5.01, 0.25)
y = np.arange(-5.01, 5.01, 0.25)
xx, yy = np.meshgrid(x, y)
z = np.sin(xx**2+yy**2)
f = interpolate.interp2d(x, y, z, kind='cubic')

In [113]:
K_list = df_call.index.astype('float')
T_list = (df_call.columns - datetime(2021,4,7)).days /365
TT, KK = np.meshgrid(T_list, K_list)
Get_Price = interpolate.interp2d(TT, KK, df_call.values.astype("float"), kind='linear')

In [119]:
Get_Price(3, 3500)

array([0.13544516])

In [24]:
IV(S_0, curr_date, r, K, end_date, isCall)

ValueError: f(a) and f(b) must have different signs

In [122]:
S = np.zeros((100, 1250))
S[:,0]
for i in range(1, len(all_dates)):
    # underlying dynamics
    t = self.all_dates[i]
    t_1 = self.all_dates[i - 1] 
    dt = (t - t_1).days/252
    r = self.Curve.get_Forward(t_1,t)
    
    S[:,t] = S[:,t-1] * np.exp((r - self.q - 0.5 * self.vol ** 2) * dt + self.vol * np.random.normal(size = (5, 10)) * np.sqrt(dt))

array([[ 1.07240828,  1.4344013 , -0.42523351, -0.04618129, -1.06188662,
         2.35604344,  0.20182271,  0.59826375, -0.09827306, -0.53155948],
       [-0.40351618, -0.59760833,  0.70091187,  0.73541999, -0.12355427,
        -1.9843561 ,  0.54348311, -0.14594497,  1.55893018,  0.4020736 ],
       [ 0.61051238,  0.02091255,  0.73986058, -0.82087086, -1.77118756,
         0.60170873, -0.92964157,  2.47034793, -1.82209004, -1.11200278],
       [ 2.00320846,  0.99597457,  0.37160758, -0.02512537, -0.36800559,
         0.47913151, -1.74626871, -0.28643363, -2.63602068, -0.90828621],
       [ 0.8944287 , -0.89534267, -1.9183885 , -0.79122377, -1.84503495,
         1.06950978, -0.04295094,  0.85067607,  0.51325397,  1.13286252]])

In [123]:
np.random.normal(size = 10)

array([ 1.34272468,  1.02751667,  1.70041009,  1.17551205,  0.77280892,
        0.61932527, -0.20591433, -1.11622472,  0.37320483,  1.70215167])